
jobs:
    main:
        requires: [~commit, ~pr, ~sd@11:builder]
        image: node:12
        steps:
            - echo: echo $SD_JOB_ID
            - sleep: sleep 10
    main-2:
        requires: [~commit, ~pr, ~sd@11:main]
        image: node:12
        steps:
            - echo: |
                echo $SD_JOB_ID
                sleep 60

